# Generated by Django 3.1 on 2021-05-18 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20210518_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_online',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
